import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"

import { THEME_STORAGE_KEY } from "@/constants/values"
import { ThemeColorProvider } from "@/components/providers/theme-color-provider"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
          storageKey={THEME_STORAGE_KEY}
        >
          <ThemeColorProvider>{children}</ThemeColorProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
